admin:
  user: admin
  password: admin123

service:
  enabled: true
  type: LoadBalancer

ingress:
  enabled: true
  hosts:
    - grafana.local
  annotations:
    kubernetes.io/ingress.class: nginx

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-server.monitoring.svc.cluster.local:9090
    access: proxy
    isDefault: true
