adminUser: admin
adminPassword: admin123
service:
  type: LoadBalancer  # Exponer Grafana con un LoadBalancer
  port: 80
ingress:
  enabled: false  # Deshabilitar el uso de Ingress
sidecar:
  datasources:
    enabled: true
  dashboards:
    enabled: true

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-server.monitoring.svc.cluster.local:9090
    access: proxy
    isDefault: true
