adminUser: admin
adminPassword: admin123
service:
  type: LoadBalancer  # Exponer Grafana con un LoadBalancer
  port: 80
ingress:
  enabled: false  # Deshabilitar el uso de Ingress
  annotations: {}
  hosts: []
  tls: []

sidecar:
  datasources:
    enabled: true
  dashboards:
    enabled: true

grafana:
  defaultDashboardsEnabled: true
  rbac:
    create: true
  serviceAccount:
    create: true


datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-server.monitoring.svc.cluster.local:9090
    access: proxy
    isDefault: true
