persistence:
  enabled: true
  existingClaim: grafana-pvc  # Usa el PVC existente de Grafana
  storageClassName: gp2  # Asegúrate de que este StorageClass esté configurado en tu cluster
  size: 10Gi  # Tamaño del almacenamiento que deseas para Grafana

adminPassword: 'EKS!sAWSome'

service:
  type: LoadBalancer  # Tipo de servicio para acceso externo
