repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: prometheus
    values:
      - prometheus-values.yaml

  - name: grafana
    chart: grafana/grafana
    namespace: grafana
    values:
      - grafana-values.yaml