repositories:
  - name: nginx-stable
    url: https://charts.nginx.com/stable
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: nginx
    namespace: default
    chart: nginx-stable/nginx-ingress
    values:
      - nginx-values.yaml

  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    values:
      - prometheus-values.yaml

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - grafana-values.yaml
