name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify the Terraform version

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1  # Specify AWS region

      # Step 4: Initialize Terraform
      - name: Terraform Init
        working-directory: terraform/aws/environments/dev
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        working-directory: terraform/aws/environments/dev
        run: terraform plan -var-file="terraform.tfvars"

      # Step 6: Manual Approval for Apply
      - name: Await Manual Approval for Apply
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ secrets.APPROVERS }}
          minimum-approvals: 1  
          issue-title: "Approval needed: Deploy to AWS"
          issue-body: "Please approve or deny the deployment of Terraform changes to the AWS environment."
          exclude-workflow-initiator-as-approver: false

      # Step 7: Terraform Apply (Auto-Approve after approval)
      - name: Terraform Apply
        if: ${{ success() }}  
        working-directory: terraform/aws/environments/dev
        run: terraform apply -var-file="terraform.tfvars" -auto-approve

  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # Step 4: Manual Approval for Destroy
      - name: Await Manual Approval for Destroy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ secrets.APPROVERS }}
          minimum-approvals: 1  
          issue-title: "Approval needed: Destroy Terraform Resources"
          issue-body: "Please approve or deny the destruction of Terraform-managed resources in the AWS environment."
          exclude-workflow-initiator-as-approver: false

      # Step 5: Terraform Destroy (Auto-Approve after approval)
      - name: Terraform Destroy
        if: ${{ success() }}  
        working-directory: terraform/aws/environments/dev
        run: terraform destroy -var-file="terraform.tfvars" -auto-approve
